version: '3.8'

services:
  app:
    image: 'imgtotext'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:8080'
    volumes:
      - '.:/app'
    command: flask run --host=0.0.0.0 --port=8080 --reload --debug
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_EXTRA_FILES=/app/app
      - FLASK_PORT=8080
  app-prod:
    image: 'imgtotext'
    ports:
      - '4001:8080'
    depends_on:
      - app