name: Python Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  IMAGE_NAME: img-to-text

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Tesseract OCR
        run: |
          sudo apt-get update
          sudo apt-get install tesseract-ocr -y
      - name: Test
        run: |
          cd app
          pytest

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME .
